### ISSUE TITLE
dateext stumbles over its own feet, aborts with File exists

### ISSUE THREAD

**Issue by KlausThornProgrammfabrik** [logrotate/logrotate#3] opened 2015-09-02 12:47 UTC
logrotate    3.8.1-4  in debian 7 (wheezy)

The config file fooconf:

```
/var/tmp/foo-foo.log {
        daily
        rotate 7
        dateext
        copytruncate
        compress
        delaycompress
        notifempty
        missingok
        su foo users
}
```

Most of the time it works, but sometimes further rotation is blocked forever.

In that case, with -d everything still seems correct:

```
logrotate -d -v --force fooconf
...
rotating pattern: /var/tmp/foo-foo.log  forced from command line (7 rotations)
empty log files are not rotated, old logs are removed
switching euid to 30012 and egid to 100
considering log /var/tmp/foo-foo.log
  log needs rotating
rotating log /var/tmp/foo-foo.log, log->rotateCount is 7
dateext suffix '-20150902'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
compressing log with: /bin/gzip
copying /var/tmp/foo-foo.log to /var/tmp/foo-foo.log-20150902
truncating /var/tmp/foo-foo.log
removing old log /var/tmp/foo-foo.log-20150812.gz
switching euid to 0 and egid to 0
```

But when I try to really make it hapen, a bug seems to take over:

```
logrotate -v --force fooconf

[exactly the same (I checked with diff)  until...]
compressing log with: /bin/gzip
error: error creating output file /var/tmp/foo-foo.log-20150818.gz: File exists
switching euid to 0 and egid to 0
```

... which all of a sudden wants to create ...20150818.gz instead of ...20150902

When looking at the files I see that there is a 0 Byte file which blocks progress:

```
-rw-r--r--   1 foo users         1,562 2015-08-16 06:37 /var/tmp/foo-foo.log-20150816.gz
-rw-r--r--   1 foo users         1,560 2015-08-17 06:39 /var/tmp/foo-foo.log-20150817.gz
-rw-r--r--   1 foo users    49,822,163 2015-08-18 06:28 /var/tmp/foo-foo.log-20150818
-rw-r--r--   1 foo users             0 2015-08-19 06:46 /var/tmp/foo-foo.log-20150818.gz
-rw-r--r--   1 foo users 1,528,347,803 2015-09-02 14:38 /var/tmp/foo-foo.log
```

... of course logrotate created that file itself, but is too dumb to not stumble over it.

After removing the file, all is well. But I would like to use dateext without manual deletions.

**Comment by hanzz** [comment] 2015-10-21 08:43
It would be great to get logs from the logrotate execution which generated `/var/tmp/foo-foo.log-20150818`, because that's the root case of the issues you see.

Could edit the crontab for logrotate execution and include `-v` flag there to get verbose output there and when the logrotate breaks again with these symptoms, then include the logrotate's output which generated that uncompresses file?

**Comment by KlausThornProgrammfabrik** [comment] 2015-10-23 08:48
OK, crontab edited.

You could, hower, just change the code to remove the zero length file - instead of aborting with "File exists". This would help other people even if the problem could not be repoduced on my server.

**Comment by KlausThornProgrammfabrik** [comment] 2016-08-03 10:48
I suspect that this is just another aspect of the "file exists" bug, as in ...

https://bugs.launchpad.net/fuel/+bug/1591026

http://de.comp.os.unix.linux.misc.narkive.com/m2BTN0bh/logrotate-error-creating-output-file-var-log-syslog-1-gz-file-exists

http://serverfault.com/a/737001

**Comment by KlausThornProgrammfabrik** [comment] 2016-08-03 10:56
I saw another on f these on a different machine ( which means: no verbose logs of the first problematic rotation).

Probably the hard disk was full, logrotate created a zero-sized ....log.1.gz and from then on chokes on this file forever (which is the bug).

reproducible verbose logrotate command output including the errors:

[logrotate_-v_output.txt](https://github.com/logrotate/logrotate/files/399271/logrotate_-v_output.txt)

config file in logrotate.d:

[logrotate_config_file_rsyslog.txt](https://github.com/logrotate/logrotate/files/399272/logrotate_config_file_rsyslog.txt)

Installed: logrotate    3.8.1-4

(debian 7.11 x86_64)

**Comment by loopsysdev** [comment] 2016-11-23 11:54
Any news on this issue? We're seeing it on a machine with `rotate 210` and `delaycompress`. It has exactly 210 compressed files, up to and including `foo.log-20160622.gz`, but *three* uncompressed files: `foo.log`, `foo.log-20160622` and `foo.log-20160623`. We tried fixing this before by removing the file which appeared as both compressed and uncompressed (`foo.log-20160622`), but the problem persisted.

**Comment by kdudka** [comment] 2016-11-23 12:11
We need some steps to reproducer the problem locally.  Are you running the latest version of logrotate?

**Comment by kdudka** [comment] 2017-04-12 08:08
No reply since November 2016.  Closing...

**Closed by kdudka** 2017-04-12 08:08 UTC
Labels: help wanted
