### ISSUE TITLE
Email subject changed when using mail + maillast

### ISSUE THREAD

**Issue by gpakosz** [logrotate/logrotate#155] opened 2017-10-08 10:54 UTC
This issue is a follow up on issue #151.

I recently when a `Wheezy` → `Jessie` → `Stretch` upgrade cycle on a Debian box.

`logrotate` package version went from: `logrotate 3.8.1-4` → `logrotate 3.8.7-1+b1` → `logrotate 3.11.0-0.1`.

After having upgraded I noticed two things:
  1. email body was not sent compressed (this the purpose of #151)
  2. email subject changed
      - previously the subject was the name of the log file being rotated, e.g. `/var/log/nginx/access.log`
      - now the subject is the name of the log file being emailed before deletion, e.g. `/var/log/nginx/access.log.366.gz`

I'm currently undecided on which behavior is correct so I'm opening this issue in hope someone with more knowledge of `logrotate` and how its options compose together can make a call.

Thanks!

**Comment by gpakosz** [comment] 2017-10-28 14:44
Any opinion on this?

**Comment by kdudka** [comment] 2018-02-06 16:34
As far as I can see, the documentation of logrotate does not specify what the correct subject is.  You did not provide any argument why the previous behavior was more correct than the current one.  I was not able to find the reasoning behind the change in logrotate's history and nobody else has commented on this.

So I tend to keep the current behavior as is and close this ticket.  The good news is that the current behavior is (partially) covered by regression tests.  So at least, it should not change again unintentionally :-)

**Comment by gpakosz** [comment] 2018-02-06 16:40
Well is `.age.gz` consistent with naming when there's no compression?

**Comment by kdudka** [comment] 2018-02-06 16:57
What do you mean exactly by _no compression_?

Log files are mailed uncompressed but, if the rotated log file was originally compressed, the suffix makes sense to me.

**Comment by gpakosz** [comment] 2018-02-07 15:32
I mean where the configuration file doesn't have `compress` nor `delaycompress`

**Comment by kdudka** [comment] 2018-02-07 16:47
Then it would indeed make no sense.  Please provide a minimal example where this happens.

**Closed** 2018-02-19 10:29 UTC
