### ISSUE TITLE
Project structure refactoring

### ISSUE THREAD

**Issue by inikolaev** [logrotate/logrotate#58] opened 2016-09-10 10:10 UTC
I would like to propose to refactor project structure a bit: move all source files (`*.c` and `*.h`) under `src` and all help(?) files under `man` or something like that.

After the change the structure would look like this:

```
man/
    logrotate.8
    logrotate.conf.5
src/
    basenames.c
    basenames.h
    config.c
    config.h
    log.c
    log.h
    logrotate.c
    logrotate.h
    queue.h
```

Let me know if there are any objections/concerns or you have other ideas about project structure.

**Comment by kdudka** [comment] 2016-09-12 07:35
Such rafactoring would complicate tracking of changes in git and complicate backporting of patches for older releases of logrotate that we maintain in enterprise Linux distributions.  What exactly would be the benefits of doing the rafactoring?  What exactly are the problems with the current structure?

I am not saying the current structure is optimal.  On the other hand, I cannot see any strong enough reason for changing it now...

**Comment by inikolaev** [comment] 2016-09-12 07:43
The advantage is that it will look a bit cleaner. Right now it looks a bit messy because source code mixed with help files, some build files and etc. 
But I didn't think about backporting changes to older versions - that indeed will make it more difficult. How often does this happen?

**Comment by kdudka** [comment] 2016-09-12 07:59
In Red Hat Enterprise Linux (RHEL) we have currently 148 logrotate bugs in Bugzilla, where 76 out of them are already fixed by a patch.  Because of our strict regression policy, we almost never updated to a newer upstream version during the life time of a major RHEL release (each supported for 10 years).  I will not speak for other distros...

**Comment by kdudka** [comment] 2016-09-12 16:41
Note that, starting with [logrotate-3.10.0](https://github.com/logrotate/logrotate/releases/tag/3.10.0), we support out-of-source builds to slightly reduce the mess (without breaking source code compatibility):
```
$ curl -Ls https://github.com/logrotate/logrotate/releases/download/3.10.0/logrotate-3.10.0.tar.xz | xz -cd | tar -x
$ cd logrotate-3.10.0
$ mkdir build && cd build && ../configure
$ make -j
```

**Comment by inikolaev** [comment] 2016-09-13 15:15
So, should I close the ticket for now? 

Also are there any plans/ideas on improving codebase in general?

**Comment by kdudka** [comment] 2016-09-13 16:24
On Tuesday, September 13, 2016 08:15:45 Igor Nikolaev wrote:
> So, should I close the ticket for now?

That would be my choice.  Others may have different opinion though.

> Also are there any plans/ideas on improving codebase in general?

Not that I know of.  There is certainly a lot of things to improve in 
logrotate's code but I am not aware of anybody working on it right now.
Feel free to have a look at possible improvements!

Ideally we should increase test coverage before doing major refactoring
to prevent unintended changes in behavior.  I found the current test-suite 
somewhat difficult to work with but have not had enough time to replace it
by anything better.

**Closed** 2016-09-16 20:42 UTC
