### ISSUE TITLE
logrotate truncates logs when rule matches a directory and a path with a symlink to this directory

### ISSUE THREAD

**Issue by cgzones** [logrotate/logrotate#218] opened 2018-08-23 05:54 UTC
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=738549:

```
In our system, each user may have a developer area within their homedir called "sites"
(eg "/home/daniel/sites"), as well as a shared directory used for hosting ("/home/apache/sites").
One of our users instead decided to make /home/user1/sites a symlink to the shared area.
That means that logrotate does rotate the logs once for the real directory, and once for
the symlink. On the second pass, it will replace the .1 file with the newly created
file which is usually empty, which means that the rotated logs are all empty.

The logrotate.d file looks like this:
  /home/web/sites/*/*.log {
    compress
    daily
    copytruncate
    delaycompress
    rotate 14
    missingok
    sharedscripts
    notifempty
    postrotate
      /etc/init.d/apache2 reload > /dev/null
    endscript
  }


The end results is logs like this:
  -rw-rw-r-- 1 www-data   www-data    98447 Feb 10 15:21 ws.log
  -rw-rw-r-- 1 www-data   www-data        0 Feb 10 09:56 ws.log.1
  -rw-rw-r-- 1 www-data   www-data       20 Feb  6 06:36 ws.log.10.gz
  -rw-rw-r-- 1 www-data   www-data       20 Feb  5 06:26 ws.log.12.gz
  -rw-rw-r-- 1 www-data   www-data       20 Feb  4 06:54 ws.log.14.gz
  -rw-rw-r-- 1 www-data   www-data       20 Feb 10 06:51 ws.log.2.gz
  -rw-rw-r-- 1 www-data   www-data       20 Feb  9 06:28 ws.log.4.gz
  -rw-rw-r-- 1 www-data   www-data       20 Feb  8 06:41 ws.log.6.gz
  -rw-rw-r-- 1 www-data   www-data       20 Feb  7 06:51 ws.log.8.gz

It also seems to skip over every even logfile number except for ".1"

May I suggest using "stat" on the result from glob, to obtain the real path
of the file, and use that when rotating and in the database? I think that
should solve many of the link related issue here.

For now we have solved this by removing the symlink, but maybe others
runs into the same problem. Marking this bug as "normal", since I would
consider this a rare issue.

Let me know if you need any more info

- Daniel
```

I tried a directory structure like:
```
$ ls -la
total 24K
drwxr-xr-x   4 root root 4.0K Aug 23 07:46 .
drwxr-xr-x. 14 root root 4.0K Aug 23 07:25 ..
drwxr-xr-x   2 root root 4.0K Aug 23 07:49 1
drwxr-xr-x   2 root root 4.0K Aug 23 07:48 2
lrwxrwxrwx   1 root root    1 Aug 23 00:06 3 -> 1
```
with a config
```
/var/log/test/*/test.log {
        daily
        sharedscripts
        postrotate
                /usr/local/sbin/test.sh $*
        endscript
        compress
        notifempty
        create
        delaycompress
        rotate 2
        mail root
        copytruncate
}
```

and when running

```
echo "test bla foo bar" >> "1/test.log"
echo "test foo bla bar" >> "2/test.log"

logrotate --verbose --force /etc/logrotate.d/test
```

multiple times, I am getting

```
$ ls -la *
lrwxrwxrwx 1 root root    1 Aug 23 00:06 3 -> 1

1:
total 12K
drwxr-xr-x 2 root root 4.0K Aug 23 07:49 .
drwxr-xr-x 4 root root 4.0K Aug 23 07:51 ..
-rw-r--r-- 1 root root    0 Aug 23 07:47 test.log
-rw-r--r-- 1 root root    0 Aug 23 07:47 test.log.1
-rw-r--r-- 1 root root   17 Aug 23 07:47 test.log.1-2018082307.backup

2:
total 16K
drwxr-xr-x 2 root root 4.0K Aug 23 07:48 .
drwxr-xr-x 4 root root 4.0K Aug 23 07:51 ..
-rw-r--r-- 1 root root    0 Aug 23 07:47 test.log
-rw-r--r-- 1 root root   17 Aug 23 07:47 test.log.1
-rw-r--r-- 1 root root   37 Aug 23 07:47 test.log.2.gz
```

**Comment by kdudka** [comment] 2018-08-23 08:43
I do not think that we should change the way how logrotate handles symlinks.  The cause of the above mentioned issues was a mistake in logrotate's configuration, which should be fixed instead.

**Closed** 2018-09-14 12:11 UTC
