### ISSUE TITLE
Weekly rotations should  ignore the timestamp in logrotate.status

### ISSUE THREAD

**Issue by NickJH** [logrotate/logrotate#93] opened 2016-12-04 09:57 UTC
If logrotate is run from cron.daily, its exact time of operation cannot be guaranteed If one week it runs at 03:20 and the following week it runs at 03:19 because one of the other cron.daily jobs took a different time to complete, the expected weekly log rotation will not happen. The same applies to daily logrotation and a day may be skipped.

I would suggest only recording a timestamp in logrotate.status when rotations are hourly (and only record them to the nearest hour). Alternatively ignore the hour/min/sec for weekly logrotates and ignore the min/sec for the hourly logrotates in any calculation of the difference between the last and current rotation.

I've posted an issue with my distro here: https://www.clearos.com/clearfoundation/social/community/clearos-7-logrotate-not-always-rotating-as-expected and there is another person with a similar issue on a different distro here: http://serverfault.com/questions/198203/how-does-logrotate-exactly-handle-daily

logrotate-3.8.6-7.el7_2.x86_64

**Comment by kdudka** [comment] 2016-12-07 15:52
I agree with your concerns about weekly rotations.  They trigger in an unpredictable way.  Could you please try the following patch?
https://github.com/logrotate/logrotate/compare/weekly

As for daily and monthly rotations, does not the code already implement what you suggest?  It seems to ignore the exact time for daily rotations (and the exact day for monthly rotations)...

**Comment by NickJH** [comment] 2016-12-07 18:59
Daily and Monthly were a leap of faith in diagnostics and if you day it works, then I'm happy to believe it.

I normally use precompiled rpms ClearOS7 (CentOS) so it will take me a while to roll my own to test.

**Comment by kdudka** [comment] 2016-12-08 12:34
On Wednesday, December 07, 2016 10:59:48 NickJH wrote:
> I normally use precompiled rpms ClearOS7 (CentOS) so it will take me a while
> to roll my own to test.

I have prepared epel7 scratch build for testing purposes:

http://koji.fedoraproject.org/koji/taskinfo?taskID=16798049

Feedback is appreciated!

**Comment by NickJH** [comment] 2016-12-08 18:31
Hi,

My distro has patched their own rpm - here is the forum thread:

https://www.clearos.com/clearfoundation/social/community/clearos-7-logrotate-not-always-rotating-as-expected

I've set up a test for tonight.

Thanks for the quick response.

Nick

**Comment by glensc** [comment] 2016-12-09 00:00
FWIW https://travis-ci.org/glensc/logrotate/builds/182450042

**Comment by NickJH** [comment] 2016-12-09 14:10
At first glance the patched version from my distro appears to work. It only rotated anything from a date 7 days ago, irrespective of the time the status file said it was rotated on that day. Ultimately it should be left to run for a few weeks before confirming the patch works, but it is looking good.

**Comment by kdudka** [comment] 2016-12-12 12:50
Thank you for testing the patch!  I will wait a few weeks before merging it as you suggest...

**Comment by NickJH** [comment] 2016-12-12 13:15
Hi,
Is there any chance you can look at this thread on ClearOS: https://www.clearos.com/clearfoundation/social/community/clearos-7-logrotate-not-always-rotating-as-expected. Another person, Tony is also testing and not getting the results he expected.
I am also wondering about how the patch is working from what he has said (I'm not a coder). If it is just ignoring the minutes and seconds to determine when log rotation is due, then there may be an issue. In ClearOS (and therefore probably CentOS and RHEL), anaconda fires cron.daily at 03:22, but has a randomness of up to 45 minutes attached to this time. This means it can conceivably fire after 04:00. Would this introduce an hour delay in logrotate.status timestamps? If it does, rotation will eventually always creep backwards, because once 03:00 goes to 04:00 there is no way back to 03:00 and eventually it may slip to 05:00 and so on.

**Comment by kdudka** [comment] 2016-12-12 14:29
Tony thinks that the patch causes logrotate to write zeros to hours and minutes in the state file.  But the patch is not supposed to do anything like that.  Is he still using the sed-based workaround by mistake?

The records in the state file should still contain the actual time stamp of the last rotation.  The only difference is that hours and minutes are now ignored while evaluating the ```weekly``` directive.  So if the last rotation happened on Sunday (any time), the next rotation will happen on Sunday, at the time when logrotate is actually invoked.

**Comment by DougSmythies** [comment] 2016-12-13 01:16
There was an alternate proposed solution to this issue on a [Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825776).

**Comment by kdudka** [comment] 2016-12-13 19:30
On Monday, December 12, 2016 17:16:37 DougSmythies wrote:
> There was an alternate proposed solution to this issue on a [Debian bug
> report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825776).

Is it really a solution?  It would still measure the exact time elapsed since 
the last rotation, only the week would be shorter by 60 seconds.  This hardly 
classifies as a solution in my view...

**Comment by DougSmythies** [comment] 2016-12-13 20:39
> Is it really a solution? 
Yes, I believe it is a good solution.

> It would still measure the exact time elapsed since
> the last rotation, only the week would be shorter by 60 seconds.
Actually it introduces a tolerance on the "has it been a week?" calculation of +0% and -0.001%, which I agree is too tight. I was suggesting something like 10 minutes, or 600 seconds ( -1 %). Whatever the number is it just has to large enough to cover the maximum expected jitter.

My distro is Ubuntu, and a related thread is [here](https://ubuntuforums.org/showthread.php?t=2320149
).
And the related bug report is [here](https://bugs.launchpad.net/ubuntu/+source/logrotate/+bug/1649168).

Note: While not new to git, I am new to GitHub, and so need some time to learn before I can pull, compile and test from here.

**Comment by NickJH** [comment] 2016-12-13 20:46
In ClearOS so possibly CentOS and RHEL as well, logrotate is fired
    by cron.daily. Cron.daily is fired by anacron and the default set up
    in anacron is with 45 minute randomness from 03:22:00, so you need
    quite a big window - and that is before you add in the jitter from
    the preceding corn.daily jobs.
    
    On 13/12/2016 20:39, DougSmythies
      wrote:
    
    
      
        Is it really a solution?
          Yes, I believe it is a good solution.
      
      
        It would still measure the exact time elapsed since
          the last rotation, only the week would be shorter by 60
          seconds.
          Actually it introduces a tolerance on the "has it been a
          week?" calculation of +0% and -0.001%, which I agree is too
          tight. I was suggesting something like 10 minutes, or 600
          seconds ( -1 %). Whatever the number is it just has to large
          enough to cover the maximum expected jitter.
      
      My distro is Ubuntu, and a related thread is here.
        And the related bug report is here.
      Note: While not new to git, I am new to GitHub, and so need
        some time to learn before I can pull, compile and test from
        here.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/logrotate/logrotate","title":"logrotate/logrotate","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/logrotate/logrotate"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DougSmythies in #93: \u003e Is it really a solution? \r\nYes, I believe it is a good solution.\r\n\r\n\u003e It would still measure the exact time elapsed since\r\n\u003e the last rotation, only the week would be shorter by 60 seconds.\r\nActually it introduces a tolerance on the \"has it been a week?\" calculation of +0% and -0.001%, which I agree is too tight. I was suggesting something like 10 minutes, or 600 seconds ( -1 %). Whatever the number is it just has to large enough to cover the maximum expected jitter.\r\n\r\nMy distro is Ubuntu, and a related thread is [here](https://ubuntuforums.org/showthread.php?t=2320149\r\n).\r\nAnd the related bug report is [here](https://bugs.launchpad.net/ubuntu/+source/logrotate/+bug/1649168).\r\n\r\nNote: While not new to git, I am new to GitHub, and so need some time to learn before I can pull, compile and test from here.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/logrotate/logrotate/issues/93#issuecomment-266855082"}}}

**Comment by kdudka** [comment] 2016-12-13 21:25
> Note: While not new to git, I am new to GitHub, and so need some time to learn before I can pull,
> compile and test from here.

If you have all dependencies installed on your system, it should be as easy as this:
```
git clone https://github.com/logrotate/logrotate.git
cd logrotate
git checkout weekly
autoreconf -fiv
./configure
make
```

**Comment by DougSmythies** [comment] 2016-12-14 08:05
@kdudka : O.K. thanks for the instructions. I am now running the proposed version of logrotate on two Ubuntu 16.04 servers.

**Comment by DougSmythies** [comment] 2016-12-14 17:11
On the two servers  running the proposed version of logrotate, my daily logs (/var/log/syslog) did not rotate last night. I also have an hourly debug run of logrotate going, as suggested by someone that was helping me with this over on Ubuntu forums:

```
rotating pattern: /var/log/syslog
 after 1 days (7 rotations)
empty log files are not rotated, old logs are removed
switching euid to 0 and egid to 109
considering log /var/log/syslog
  Now: 2016-12-14 06:45
  Last rotated at 2016-12-14 04:00
  log does not need rotating (log has been rotated at 2016-12-14 4:0, that is not day ago yet)
switching euid to 0 and egid to 0

```
It wasn't actually rotated at Last rotated at 2016-12-14 04:00. This is the status file line:

`"/var/log/syslog" 2016-12-13-4:25:1`

**Comment by kdudka** [comment] 2016-12-14 19:44
The patch in question does not change daily rotations in any way.  It looks like logrotate uses a different state file than the one you are checking manually.  Please use the ```-s``` option to specify the state file explicitly.  You can also verify the last modification time of the state file -- does it match the last invocation of logrotate?

**Comment by DougSmythies** [comment] 2016-12-14 23:16
Somewhere along the way it seems that the default location of the status file changed from /var/lib/logrotate/status to /var/lib/logrotate.status . O.K. so I am forcing the use of the old status file now, as @kdudka suggested.

I observe that the file created at , /var/lib/logrotate.status does not have any minutes or seconds information anymore. That would make it similar to Ubuntu 14.04 (Ubuntu 12.04 didn't have any hour information either), and therefore Ubuntu (>=16.04), at least wouldn't suffer from this problem anymore anyhow. I never observed this issue with Ubuntu 14.04, but noticed it in the development phase of 16.04 (around February 2016).

As for the alternate solution proposed in the Debian bug report. I suppose the tolerance could be 3600 seconds to cover the ClearOS condition.

**Comment by kdudka** [comment] 2016-12-15 08:19
On Wednesday, December 14, 2016 15:16:43 DougSmythies wrote:
> Somewhere along the way it seems that the default location of the status
> file changed from /var/lib/logrotate/status to /var/lib/logrotate.status .
> O.K. so I am forcing the use of the old status file now, as @kdudka
> suggested.

Starting with logrotate-3.11.0, you can specify the default state file path
at build time by the --with-state-file-path option of the configure script.

> As for the alternate solution proposed in the Debian bug report. I suppose
> the tolerance could be 3600 seconds to cover the ClearOS condition.

But the constant does not work as any tolerance.  It would just make the week 
one hour shorter.  Then weekly rotations would be fired too soon unexpectedly.  
Not a solution really.

**Comment by DougSmythies** [comment] 2016-12-15 17:13
> Starting with logrotate-3.11.0, you can specify the default state file path
> at build time by the --with-state-file-path option of the configure script.
O.K. thanks. My daily logs rotated properly last night, however I messed up on one server. Still a few days until weekly rotation anyhow.

> But the constant does not work as any tolerance.  It would just make the week
> one hour shorter.  Then weekly rotations would be fired too soon unexpectedly.
> Not a solution really.
I'm not following the logic. The tolerance just defines the window, the actual timing of when is defined by when logrotate actually runs. Ubuntu only runs logrotate daily. However, if logrotate is run hourly, then yes the tolerance would have to be less than an hour, to prevent the week time creeping backwards.
Actually, I don't see a problem with the unpatched code if one is running logrotate hourly, as it will just do the weekly in the next hour if jitter caused the normally desired hour to be missed.

A question: The proposed patch also deletes "if the current weekday is before the weekday of the last rotation" check. Why? I always thought weekly rotations were supposed to migrate to Sundays. If it is going to change, then does the man page have to change also?

**Comment by kdudka** [comment] 2016-12-15 18:02
On Thursday, December 15, 2016 09:13:57 DougSmythies wrote:
> I'm not following the logic. The tolerance just defines the window, the
> actual timing of when is defined by when logrotate actually runs. Ubuntu
> only runs logrotate daily.

That is a valid setup but not the only one supported by logrotate.

> However, if logrotate is run hourly, then yes
> the tolerance would have to be less than an hour, to prevent the week time
> creeping backwards. Actually, I don't see a problem with the unpatched code
> if one is running logrotate hourly, as it will just do the weekly in the
> next hour if jitter caused the normally desired hour to be missed.

logrotate needs to work correctly even if you invoke it more often.  Even if 
you invoke it in an infinite loop, weekly rotations should trigger once per 
week.

> A question: The proposed patch also deletes "if the current weekday is
> before the weekday of the last rotation" check. Why? I always thought
> weekly rotations were supposed to migrate to Sundays. If it is going to
> change, then does the man page have to change also?

Good point.  I was not aware of the actual documentation of 'weekly' in the 
man page.  If we agree that the proposed criterion is suitable for weekly 
rotation and the change in behavior is acceptable, we can just update the
man page accordingly.  If not, we will need to introduce a new directive
for predictable weekly rotations and keep the existing 'weekly' directive
as it is.

**Comment by sraellis** [comment] 2016-12-16 02:05
@kdudka wrote
> Tony thinks that the patch causes logrotate to write zeros to hours and minutes in the state file. But the patch is not supposed to do anything like that. Is he still using the sed-based workaround by mistake?

Oops - didn't read the patch in enough detail... no "sed-based workaround" was applied - just an updated test rpm from my distribution (ClearOS 7.2)

Here is an extract showing rotated logs
>-rw-------  1 root root 4864354 Dec 16 12:39 /var/log/maillog
-rw-------. 1 root root 1647992 Nov 27 03:34 /var/log/maillog-20161127
-rw-------  1 root root 2599359 Dec  4 22:55 /var/log/maillog-20161204

No logrotate last Sunday - the daily cron job did trigger logrotate between 3 and 4 am - but at that time 7 full days had not passed since the previous rotate... at 22:55! - why? this machine is 24 x 7
An extract of /var/lib/logrotate/logrotate.status - the minutes and seconds were definitely dropped 
>"/var/log/samba/log.nmbd" 2016-12-10-3:0:0
"/var/log/news.log" 2016-12-10-3:0:0
"/var/log/maillog" 2016-12-10-3:0:0
"/var/log/ntp.log" 2016-12-10-3:0:0
"/var/log/httpd/ssl_request_log" 2016-12-10-3:0:0

and lastly  /etc/cron.daily/logrotate
>#!/bin/sh
/usr/sbin/logrotate -s /var/lib/logrotate/logrotate.status /etc/logrotate.conf
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0

 Will wait to see what happens this coming Sunday. Fortunately this machine is not yet in production.

**Comment by kdudka** [comment] 2016-12-16 09:30
Which version of logrotate do you compare the behavior to?  If it is not ```logrotate -3.11.0```, you most likely observe some effect of completely unrelated changes.  If you applied the patch on an older version of logrotate, are you sure that the patch still works as intended?

**Comment by sraellis** [comment] 2016-12-18 01:37
@kdudka 
The patch was applied by ClearOS not me...

Checked my 7.2 logs this morning to see if logrotate had worked. 
Bizarrely they had rotated *yesterday* (Saturday) morning..

>
-rw-------  1 root root  426835 Dec 18 11:39 maillog
-rw-------. 1 root root 1647992 Nov 27 03:34 maillog-20161127
-rw-------  1 root root 2599359 Dec  4 22:55 maillog-20161204
-rw-------  1 root root 5050062 Dec 17 03:31 maillog-20161217

Checked /var/lib/logrotate/logrotate.status and entries now have the standard format

>
"/var/log/saslauthd.log" 2016-12-17-3:35:8
"/var/log/banned_ip.txt" 2016-12-17-3:35:8
"/var/log/syswatch" 2016-12-17-3:35:8
"/var/log/dhcpd.log" 2016-12-17-3:35:8
"/var/log/named.log" 2016-12-17-3:35:8
"/var/log/imap.log" 2016-12-17-3:35:8

Have edited the entries to look like 'xxxxxxxxx 2016-12-18-3:35:8' - will see what happens next week.

**Comment by DougSmythies** [comment] 2016-12-19 07:05
I would leave the first condition:

> 1) the current weekday is before the weekday of the last rotation 

unaltered.
But apply your proposed algorithm change to the second condition:

> 2) more then a week has passed since the last rotation */

However, change that comment text to read;

>  2) a week or more has passed since the last rotation */

For my part of it, I did not realize that the initial status file only has information to the hour, but subsequent file information is to the second. I had to re-visit some old test results.

**Comment by NickJH** [comment] 2017-01-08 07:54
Since I installed a patched version of 3.8.6-12 on 8 Dec, it has been working OK on my system. Thanks

**Comment by kdudka** [comment] 2017-01-09 11:31
On Saturday, January 07, 2017 23:54:30 NickJH wrote:
> Since I installed a patched version of 3.8.6-12 on 8 Dec, it has been
> working OK on my system. Thanks

Thank you for testing it!

I have pushed one more commit to update the man page in the 'weekly' branch:

https://github.com/logrotate/logrotate/commit/12a7adc3

**Comment by DougSmythies** [comment] 2017-01-09 15:41
Please reconsider. You are introducing a fundamental change to how weekly logrotate has always worked.

**Comment by kdudka** [comment] 2017-01-09 20:34
@DougSmythies see https://github.com/logrotate/logrotate/issues/93#issuecomment-267397203 where I proposed two options:

1. If we agree that the proposed criterion is suitable for weekly rotation and the change in behavior is acceptable, we can just update the man page accordingly.

2. If not, we will need to introduce a new directive for predictable weekly rotations and keep the existing 'weekly' directive as it is.

Nobody had a strong opinion about any of them so far...

You can see that the ```weekly``` branch is not yet merged into master.  Even if it was, I am still open to discussion until the new behavior actually reaches an official release of logrotate.

**Comment by NickJH** [comment] 2017-01-09 20:42
I have to say that I disagree with DougSmythies. As far as I am aware, logrotate never used to record the time of the previous rotation, just the date. All this patch is doing is effectively reverting to the behaviour before the time was recorded. My knowledge may be about old releases, but I believe that is how it used to work in the past. Weekly should continue to operate in the same way. If you want something where it can fall back a day if the elapsed time is just under one week, then this new behaviour should have a new directive.

**Comment by DougSmythies** [comment] 2017-01-09 22:57
@NickJH I totally agree that logrotate used to only record the date, and the issue was introduced because the time to the second was added. However, the proposed patch also changes the first of two very very old conditions, "the current weekday is before the weekday of the last rotation". That condition should not be changed, as it is a non-backwards compatible change.

@kdudka I did comment above. And please know that I had checkout the earliest versions logrotate available when looking into this stuff.

**Comment by DougSmythies** [comment] 2017-01-09 23:11
I am saying that the man page edits should be deleted and that this should be done instead:

```
	    /* rotate if:
	       1) the current weekday is before the weekday of the
	       last rotation
	       2) more then a week has passed since the last
	       rotation (exact time is ignored) */
	    state->doRotate = ((now.tm_wday < state->lastRotated.tm_wday)
			       ||
 		((mktimeFromDateOnly(&now) -
 		  mktimeFromDateOnly(&state->lastRotated)) >= (7 * 24 * 3600));

```

**Comment by kdudka** [comment] 2017-01-10 08:25
On Monday, January 09, 2017 15:11:30 DougSmythies wrote:
> I am saying that the man page edits should be deleted and that this should
> be done instead:
> 
> ```
> 	    /* rotate if:
> 	       1) the current weekday is before the weekday of the
> 	       last rotation
> 	       2) more then a week has passed since the last
> 	       rotation (exact time is ignored) */
> 	    state->doRotate = ((now.tm_wday < state->lastRotated.tm_wday)
> 
>  		((mktimeFromDateOnly(&now) -
>  		  mktimeFromDateOnly(&state->lastRotated)) >= (7 * 24 * 3600));
> 
> ```

What you are proposing just combines the bad outcomes of both the solutions:

1) It changes the current behavior without providing a way to restore it.

2) It does not solve the problem at all because weekly rotations could still  
trigger too early, depending on how regularly you call logrotate.

We simply need a directive that triggers rotation _exactly_ once per week, 
assuming logrotate is invoked at least once a day.  The only options are:

1) Fix the current 'weekly' directive to work such and update the man page.

2) Keep the current (IMO broken) 'weekly' directive as it is and introduce
a new directive for predictable weekly rotations.

3) Fix the current 'weekly' directive and introduce a new directive to enable 
the old behavior in case anyone needed it.

Note that option 3) will still be available even after the release is out.

**Comment by kdudka** [comment] 2017-01-11 11:26
@glensc What is your opinion on this?  Should we keep the old semantics of the ```weekly``` directive?

**Comment by DougSmythies** [comment] 2017-01-13 07:07
I won't say anymore, as it would just be repetitive. I did add a note on both the Ubuntu and Debian downstream bug reports that stake holders should chime in here. That was a few days ago, and they haven't.

**Comment by kdudka** [comment] 2017-01-13 07:50
On Thursday, January 12, 2017 23:07:35 DougSmythies wrote:
> I did add a note on both the Ubuntu and Debian downstream bug reports that
> stake holders should chime in here.

Thanks!  I believe it could help us to collect some feedback before making
the final decision.

> That was a few days ago, and they haven't.

I guess you should give them more time to reply before making a conclusion.

Anyway, I am not sure that you are explaining the condition being removed
correctly.  You say "migration to Sunday", which is somewhat misleading
because it does not make logrotate trigger the rotation on first Sunday.
If you first rotate on Saturday, the next rotation will trigger on Friday,
then on Thursday, ..., and the actual Sunday's rotation would trigger 6
weeks later.  Then, if the machine is down for a couple of days (including
Sunday), the rotation is moved to another day of the week and the migration
process starts over.

Also it is not clear to me why we should prefer rotations on Sunday.  Some
users need to rotate on Wednesday:

http://askubuntu.com/questions/704235/how-to-change-the-day-of-the-week-logrotate-shifts-the-file-when-configured-week

What about making the 'weekly' predicate optionally configurable to rotate
on a selected day of the week?

**Comment by DougSmythies** [comment] 2017-01-13 15:41
> You say "migration to Sunday", which is somewhat misleading
> because it does not make logrotate trigger the rotation on first Sunday.
> If you first rotate on Saturday, the next rotation will trigger on Friday,
> then on Thursday, ..., and the actual Sunday's rotation would trigger 6
> weeks later.

No, it will switch to Sundays on the first Sunday.
Saturday = day 7, Sunday = day 0, which is less than day 7.

> Also it is not clear to me why we should prefer rotations on Sunday.  Some
> users need to rotate on Wednesday:

Well, me either. It is just that is how it has always been, and if you change it, it is not backwards compatible, and therefore will make obsolete lots of stuff written about how it currently works. (and Linux in general does not seem to worry about backwards compatibility, or the ripple effect to documentation) However, and as we all know, lots of stuff written on internet is wrong anyhow.

> What about making the 'weekly' directive optionally configurable to rotate
> on a selected day of the week?

If I understand correctly, that the default would be the way it is now, that would be a great idea.

If the downstream stakeholders don't chime in, then you can discard my input here. In an attempt to get the original issue fixed, I was merely following it upstream and found this. However, I am not a downstream maintainer or anything. It was not intent to be annoying.
Thanks for your work on this.

**Comment by kdudka** [comment] 2017-01-13 16:27
On Friday, January 13, 2017 07:41:49 DougSmythies wrote:
> No, it will switch to Sundays on the first Sunday.

Indeed.  My example was incorrect.  Thank you for pointing it out!

> Saturday = day 7, Sunday = day 0, which is less than day 7.

Saturday is day 6 but otherwise you are right.

> Well, me either. It is just that is how it has always been, and if you
> change it, it is not backwards compatible, and therefore will make obsolete
> lots of stuff written about how it currently works.

Then I wonder why the documentation of the 'weekly' directive in logrotate.8 
man page does not say Sundays explicitly.  The current wording is IMO too 
cryptic for nothing.  Moreover, it does not say that numbering days of a week 
ignores locale settings, which could surprise some users.

> If I understand correctly, that the default would be the way it is now, that
> would be a great idea.

Not that I meant it initially but, yes, it makes perfect sense now!  I will 
prepare a patch to fix it (to some extent) in a backward compatible way...

**Comment by NickJH** [comment] 2017-01-13 16:59
As a thought, you could allow the parameter WEEKLY to take an extra parameter e.g. "WEEKLY 0" for a weekly rotation on Sunday.

It does raise a question. If you then use "WEEKLY 0" and the last rotation was the previous Tuesday, does it do the next rotation on the Sunday (so less than a 1 week period) or does it skip a week (enforcing a minimum of 1 week). I'd probably prefer the former.

The other question is what you do if a rotation has been skipped, E.g  if you are on WEEKLY 0 and your system was down for the weekend. I'd say you immediately rotate. Then you get back to my first question.

**Comment by DougSmythies** [comment] 2017-01-14 16:51
> Saturday is day 6 but otherwise you are right.

Ops. Yes, of course.

> The other question is what you do if a rotation has been skipped, E.g if you are on WEEKLY 0
> and your system was down for the weekend. I'd say you immediately rotate.
> Then you get back to my first question.

I have an older Ubuntu 12.04 server that is normally turned off (it is a backup for the backup computer). So, it is running quite an old version of logrotate (3.7.8-6ubuntu5) from before when it got broken. I started it yesterday, Friday, after it had been off for about 3 weeks. And indeed weekly log rotations occurred this morning, Saturday.

> It does raise a question. If you then use "WEEKLY 0" and the last rotation was the previous
> Tuesday, does it do the next rotation on the Sunday (so less than a 1 week period)
> or does it skip a week (enforcing a minimum of 1 week). I'd probably prefer the former.

I'll leave the computer on until tomorrow, Sunday, and report back.

**Comment by NickJH** [comment] 2017-01-14 18:16
>>   It does raise a question. If you then use "WEEKLY 0" and the last rotation was the previous
    Tuesday, does it do the next rotation on the Sunday (so less than a 1 week period)
    or does it skip a week (enforcing a minimum of 1 week). I'd probably prefer the former.

 >   I'll leave the computer on until tomorrow, Sunday, and report back.

That comment was only really if you went with my idea of an extra parameter and which strategy do you use to get back to the required rotate day

**Comment by DougSmythies** [comment] 2017-01-15 16:54
> That comment was only really if you went with my idea of an extra parameter
> and which strategy do you use to get back to the required rotate day

Yes, I know. I'm just providing data from how it worked before it got broken.
And the weekly logs did rotate again this morning, Sunday.

It is unclear to me why this issue was set to closed.

**Comment by kdudka** [comment] 2017-01-19 17:49
Could you please try the following patch?
https://github.com/logrotate/logrotate/commit/034a7bdb13706454064287b25187a0d12e6afdee

It rotates on Sunday by default but ```weekly``` takes an optional argument to change it to another day of the week.  ```weekly 7``` can be used to rotate once per week, irrespectively of the weekday.  I tried to describe it in the ```logrotate.8``` man page.

**Comment by kdudka** [comment] 2017-01-23 13:26
Rebased on top of current master: bd2638856dbbb6c0a47beb85fe8a8a628160772e

Any feedback is appreciated!

**Comment by DougSmythies** [comment] 2017-01-23 16:23
I was running 3 computers with 034a7bd, and have now updated them with bd26388. Two computers will just continue to run normally, and the weekly log rotations did work normally yesterday (Sunday). The third computer is the normally turned off one mentioned above. I'm just checking default behaviour. I'll report back in a week or more.

**Comment by NickJH** [comment] 2017-01-23 16:36
Sorry, but I don't really have the ability to patch the files and generate my own rpm's. :(

**Comment by kdudka** [comment] 2017-01-23 22:42
@NickJH could you please try ```logrotate-3.11.0-2.2.el7 ``` from the following copr?
https://copr.fedorainfracloud.org/coprs/kdudka/logrotate-testing/

**Comment by sraellis** [comment] 2017-01-23 23:16
Installed logrotate-3.11.0-2.2.el7 on ClearOS version 7.3 Beta
Will update when a logrotate occurs...

**Comment by NickJH** [comment] 2017-01-24 17:47
Thanks, I've just installed it. I'll let it run naturally tonight before trying to modify the WEEKLY parameter

**Comment by NickJH** [comment] 2017-01-29 09:46
Apologies for closing the bug earlier. I must have hit the wrong button when commenting.

On Thursday I set the global parameter to "WEEKLY 5" and in my openvpn rotate definition to "WEEKLY 6". In the early hours of Friday morning, most logs rotated and the openvpn log did not. On Saturday morning the openvpn log rotated but not the others. I then reverted and removed the 5/6 and this morning (Sunday) everything rotated. Where I left ipsec to rotate without a day qualifier, it only rotated on Sunday morning.

If the logic is meant to be rotate on whichever is the earlier, weekly or the day specified, the I am comfortable with the logic as it gets onto the specified day as soon as possible and the patch appears to be working.

Thanks.

**Comment by DougSmythies** [comment] 2017-01-29 16:43
> I was running 3 computers with 034a7bd, and have now updated them with bd26388.
> Two computers will just continue to run normally, and the weekly log rotations
> did work normally yesterday (Sunday).
> The third computer is the normally turned off one mentioned above.
> I'm just checking default behaviour. I'll report back in a week or more.

The two always on servers did weekly log rotations normally early this morning (Sunday).
The normally off computer did a log rotation the first night, as expected as it had been off for over a week, and it also did the normal rotation early this morning.
Conclusion: seems fine. Thanks.

**Comment by sraellis** [comment] 2017-01-29 23:52
Logrotate ran Sunday morning OK

/var/log/cron-20170129:Jan 27 03:16:52 alex run-parts(/etc/cron.daily)[26590]: starting logrotate

Sorry, not willing to play with the parameters as I have jobs that analyse some of the log files and expect the  yyyymmdd suffix to be a Sunday, and to have run before 4 am - missing a week is no problem - running late or on on a different day is...

**Comment by kdudka** [comment] 2017-01-31 09:38
Thanks to all who tested this!  I am merging the patch into master...

**Closed** 2017-01-31 09:38 UTC
