### ISSUE TITLE
logrotate -f returns always 1

### ISSUE THREAD

**Issue by aicastell** [logrotate/logrotate#9] opened 2015-12-09 12:13 UTC
Why logrotate is returning code error 1 when it is executed with flag -f?

**Comment by hanzz** [comment] 2015-12-18 12:19
It does not for me. What's the config file you are using and please send the output produced in verbose mode (-v) flag.

**Comment by aicastell** [comment] 2015-12-18 12:29
$ cat /etc/logrotate.conf 
# rotate log files daily
# daily

# keep 7 days worth of backlogs
# rotate 7

# create new (empty) log files after rotating old ones
# create

# uncomment this if you want your log files compressed
compress

# do not rotate the log if it is empty
notifempty

# system-specific logs may be configured here
include /etc/logrotate.d

$ cat /etc/logrotate.d/varlog
/var/log/*log {
	daily
	missingok
	copytruncate
	rotate 5
	maxage 5
	dateext
	olddir /var/vlt/logrotate
}

$ logrotate -v
logrotate 3.9.1 - Copyright (C) 1995-2001 Red Hat, Inc.
This may be freely redistributed under the terms of the GNU Public License

Usage: logrotate [-dfv?] [-d|--debug] [-f|--force] [-m|--mail=command]
        [-s|--state=statefile] [-v|--verbose] [-l|--log=STRING] [--version]
        [-?|--help] [--usage] [OPTION...] <configfile>

**Comment by sc-perth** [comment] 2016-10-22 20:11
You must specify the config file when using ```logrotate -f```.
Example of correct method: ```logrotate -f /etc/logrotate.conf```

```Usage: logrotate [-dfv?] [-d|--debug] [-f|--force] [-m|--mail=command] [-s|--state=statefile] [-v|--verbose] [-l|--log=STRING]
        [--version] [-?|--help] [--usage] [OPTION...] <configfile>```
Note the ```<>``` brackets indicate a required argument.

**Comment by kdudka** [comment] 2016-10-24 11:31
Indeed.  This looks like just incorrect usage.  @aicastell could you please provide the full command-line of logrotate's invocation for which it happens?

**Comment by aicastell** [comment] 2016-10-29 06:10
Thank you for your suggestions. I don't have the testing environment available now. But I remember to use exactly the suggested command (as man says, config_file is NOT optional). logrotate was doing its job fine, and when returning to shell, "1" was printed when echoing $? environ variable. I should re-install a test environment again to reproduce the exact behaviour and check it again. I will come back when I could prepare it again.

**Comment by kdudka** [comment] 2017-04-10 07:31
I am closing this for now.  Please open a new issue when you have steps to reproduce the bug.

**Closed by kdudka** 2017-04-10 07:31 UTC
