### ISSUE TITLE
logrotate erroring out when removing the extra file

### ISSUE THREAD

**Issue by andreiiar** [logrotate/logrotate#110] opened 2017-03-14 09:06 UTC
We have this error 

```
/etc/cron.daily/logrotate:
error: error opening /var/spool/exim4/dmarc_history.11.gz: No such file or directory
run-parts: /etc/cron.daily/logrotate exited with return code 1                                                
```

We have 10 days logs, dmarc_history.11.gz should be removed at this step.

I cannot reproduce it and it happens from time to time.

```
/var/spool/exim4/dmarc_history {
        daily
        missingok
        rotate 10
        compress
        delaycompress
        create 640 Debian-exim Debian-exim
        su Debian-exim Debian-exim
        postrotate
                       [REMOVED]
        endscript
}

```

**Comment by kdudka** [comment] 2017-03-14 09:58
I am afraid we do not have enough data to tell you anything useful.  Are you running the latest release of logrotate?  Could you please capture the output of ```logrotate -v``` when it happens?

**Comment by kdudka** [comment] 2017-05-02 10:48
Closing until the required info is provided.

**Closed by kdudka** 2017-05-02 10:48 UTC

**Comment by gp4git** [comment] 2017-09-14 09:46
Hello,
I get the same problem with logrotate 3.8.6 and it manifests since we reached the rotate count given in the rotate directive (31 in my case).

Here is the output in verbose mode, I got last night :
rotating pattern: /var/log/pgsql96/pgsql96.log  after 1 days (31 rotations)
empty log files are not rotated, old logs are removed
considering log /var/log/pgsql96/pgsql96.log
  log needs rotating
rotating log /var/log/pgsql96/pgsql96.log, log->rotateCount is 31
dateext suffix '-20170914'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
compressing log with: /bin/gzip
fscreate context set to unconfined_u:object_r:var_log_t:s0
renaming /var/log/pgsql96/pgsql96.log to /var/log/pgsql96/pgsql96.log-20170914
creating new /var/log/pgsql96/pgsql96.log mode = 0640 uid = 26 gid = 26
running postrotate script
removing old log /var/log/pgsql96/pgsql96.log-20170814.gz
error: error opening /var/log/pgsql96/pgsql96.log-20170814.gz: No such file or directory

Is it now a known problem ?

Regards

**Comment by kdudka** [comment] 2017-09-14 11:09
@gp4git Please open a new issue with self-contained steps to reproduce it.

**Comment by gp4git** [comment] 2017-09-14 12:08
OK I will do that even if I think this is a duplicate.

Regards
