### ISSUE TITLE
[Feature Request] Random Wait functionality

### ISSUE THREAD

**Issue by bryaend** [logrotate/logrotate#428] opened 2021-11-05 20:21 UTC
For environments with hundreds of VMs and large amounts of logging, it would be beneficial to have the option to run the logrotate at the same time (e.g., midnight) for all servers but allow them to pause for a random time (e.g., anywhere from 0 seconds to 6 hours, etc.) to more evenly distribute the processing load to compress so many files on so many servers. This would reduce nightly large CPU spikes across large clusters of hypervisors but still allow logs to be rotated at midnight sharp.

**Comment by kdudka** [comment] 2021-11-07 07:31
Do you trigger logrotate by the systemd timer?  The `AccuracySec=1h` option in `logrotate.timer` does exactly this.

**Comment by cgzones** [comment] 2021-11-09 16:57
This seems to be a duplicate of #403.

See https://github.com/logrotate/logrotate/issues/403#issuecomment-864058675 for a suggested solution.

Another idea is to use `postrotate` and write the passed rotated filename to a file and compress all entries in this file with another timer in the desired timeframe.

**Comment by Zugschlus** [comment] 2022-04-03 13:55
> Do you trigger logrotate by the systemd timer? The `AccuracySec=1h` option in `logrotate.timer` does exactly this.

No, it doesn't. The requestor wants logrotate to wait a random time between actual log rotation (which causes next to no load) and the compression (which causes load). Your suggestion will also spread out the rotation, making it significantly harder to put logs taken around the rotation time on different machines side-by-side.

**Closed** 2022-12-02 15:50 UTC
