### ISSUE TITLE
logrotate started by systemd OnBootSec: result is no-op

### ISSUE THREAD

**Issue by InvisibleMass** [logrotate/logrotate#402] opened 2021-06-12 20:35 UTC
On a
`Linux xxxxx 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`
system I am trying to run logrotate only at system boot and not at any other schedule.
Logrotate version is 3.14.0 as installed by the Debian system installer.

/etc/logrotate.conf contains:
```
weekly
rotate 99
create
dateext
dateformat .%Y.%m.%d.%H.%M.%S
include /etc/logrotate.d
```
Using
`systemctl edit logrotate.timer`
`/etc/systemd/system/logrotate.timer.d/override.conf`
contains:

```
[Unit]
Description=
Description=On boot rotation of log files

[Timer]
OnCalendar=
OnBootSec=2
AccuracySec=1
```

Using
`systemctl edit logrotate.service`
`/etc/systemd/system/logrotate.service.d/override.conf`
contains:

```
[Unit]
ConditionACPower=
RequiresMountsFor=/var/log

[Service]
ExecStart=
ExecStart=/usr/sbin/logrotate -fv /etc/logrotate.conf
```
After boot and login, systemctl status shows logrotate.timer as loaded active elapsed and logrotate.service as loaded inactive dead.
`Systemctl show logrotate.service --property=ExecMainstatus`
reports ExecMainStatus=0.

`systemd-analyze verify logrotate.timer` and
`systemd-analyze verify logrotate.service`
report nothing.

`systemd-analyze critical-chain logrotate.service`
shows the expected behavior, running @2.005s (with sysinit.target @1.984s).

However, an actual logrotate did not take place at system startup. I see no error messages in any logfile (but maybe I am not looking at the right places). Anything else looks fine.

When I run
`logrotate -fv /etc/logrotate.conf`
manually, the log rotation is executed as expected. So, I assume no logrotate setup error.

I am a bit clueless, what the actual problem is, why logrotate is not running as expected.
Any ideas, anybody?

Best regards...

**Comment by kdudka** [comment] 2021-06-14 08:06
I am not a systemd expert but I guess you need to disable the timer and enable the service if you want to run logrotate on boot rather than periodically?
```
systemctl disable logrotate.timer
systemctl enable logrotate.service
```

**Comment by kdudka** [comment] 2021-06-14 08:09
... and maybe add something like this to the unit file:
```
[Install]
WantedBy=multi-user.target
```

**Comment by cgzones** [comment] 2021-06-14 15:08
If you want to run logrotate once at boot time you have two options:

1. Set the timer at `OnBootSec=X` as you did.
    But you specified `ExecStart=` twice, which I think is not supported without `Type=oneshot` (which I think is missing in your override), see https://www.freedesktop.org/software/systemd/man/systemd.service.html .
2.  Delete the timer and run the service with:
     ```
     [...]
     RemainAfterExit=yes
     [Install]
     WantedBy=multi-user.target
     ```

**Comment by InvisibleMass** [comment] 2021-06-14 16:33
>        But you specified `ExecStart=` twice, which I think is not supported without `Type=oneshot` (which I think is missing in your override), see https://www.freedesktop.org/software/systemd/man/systemd.service.html .

It actually IS Type=oneshot from the default installation.
 
>     2. Delete the timer and run the service with:
>        ```
>        [...]
>        RemainAfterExit=yes
>        [Install]
>        WantedBy=multi-user.target
>        ```

Did this, but with variation to
WantedBy=sysinit.target

Then disabled logrotate.timer and re-enabled logrotate.service.
Seems to work now.

Could be configured better, I think, because a considerable amount of messages of the 'current' boot goes into the 'old' logfiles. So, WantedBy should probably select some earlier target. If anybody has an immediate clue how to configure logrotate-service to run at the earliest possible stage in the boot process, please let me know. Would save me some trial-and-error games.

Thanks!

**Comment by InvisibleMass** [comment] 2021-06-16 21:36
I experimented and when setting

```
[Unit]
ConditionACPower=
RequiresMountsFor=/var/log
DefaultDependencies=no
After=blk-availability.service
After=lvm2-lvmpolld.socket
After=lvm2-monitor.service
Before=systemd-journal-flush.service
Before=systemd-journald.service
[Service]
ExecStart=
ExecStart=/usr/sbin/logrotate -fv /etc/logrotate.conf
RemainAfterExit=yes
[Install]
WantedBy=local-fs.target
```

via `systemctl edit logrotate.service`, it seems that syslog, kern.log and messages all start from time 0.000000.
But I am not sure that this is really a reliable way to run logrotate. For example the verbose messages written by logrotate itself do not appear anywhere anymore (except maybe for a fraction of a second on the console).

Maybe some developers can comment on this?
Are there more dependencies that need an explicit expression in the override.conf when pulling logrotate into the early boot process, before the sysinit.target? There may be dangers out there that do not show up on my specific system, but may be more harmful in other environments.

Thanks!

**Comment by kdudka** [comment] 2021-06-17 06:41
@InvisibleMass You would probably get a better answer on systemd-related channels as your question is more about systemd rather than logrotate itself.

**Comment by InvisibleMass** [comment] 2021-06-17 08:35
@kdudka I agree to a certain point, but the true dependencies of logrotate itself can only be answered by the logrotate developers (e.g.: Does it need /var/tmp ?; Does it need journald? etc...)

**Comment by kdudka** [comment] 2021-06-17 10:53
I do not think logrotate itself needs anything of those unless you explicitly configure logrotate to use it.

**Comment by InvisibleMass** [comment] 2021-06-29 13:31
I experimented around and found that the above configuration produces some negative side effects.
My current
`/etc/systemd/system/logrotate.service.d/override.conf`
now contains:

```
[Unit]
ConditionACPower=
RequiresMountsFor=/var/log
DefaultDependencies=no
Before=syslog.service
[Service]
ExecStart=
ExecStart=/usr/sbin/logrotate -fv /etc/logrotate.conf
RemainAfterExit=yes
[Install]
WantedBy=local-fs.target
```

So, it seems to be sufficient to delay syslog.service until logrotate has finished.
Combined with disabling logrotate.timer, this seems to effectively isolate the logs for each system start/shutdown - at least on an otherwise virgin Debian system (without graphical desktop). I do not observe any errors with this configuration.

...for those of you who may be interested.

**Comment by kdudka** [comment] 2021-06-29 14:41
Thanks for sharing!  I am closing this out as the issue is not related to the source code maintained in this repository.

**Closed by kdudka** 2021-06-29 14:41 UTC
Labels: systemd
